# Generated by Django 5.0.6 on 2026-03-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                (
                    "playerID",
                    models.CharField(max_length=30, unique=True, verbose_name="소환사명"),
                ),
                (
                    "playerPowerScore",
                    models.IntegerField(default=1000, verbose_name="파워 스코어"),
                ),
                (
                    "playerMainPosition",
                    models.CharField(
                        choices=[
                            ("TOP", "탑"),
                            ("JGL", "정글"),
                            ("MID", "미드"),
                            ("ADC", "원딜"),
                            ("SUP", "서폿"),
                        ],
                        max_length=3,
                        verbose_name="주 포지션",
                    ),
                ),
                (
                    "playerSecondaryPosition",
                    models.CharField(
                        choices=[
                            ("TOP", "탑"),
                            ("JGL", "정글"),
                            ("MID", "미드"),
                            ("ADC", "원딜"),
                            ("SUP", "서폿"),
                        ],
                        max_length=3,
                        verbose_name="부 포지션",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "플레이어",
                "verbose_name_plural": "플레이어 목록",
                "ordering": ["playerID"],
            },
        ),
    ]
