# Generated by Django 5.0.6 on 2026-03-09 05:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={
                "ordering": ["player_id"],
                "verbose_name": "플레이어",
                "verbose_name_plural": "플레이어 목록",
            },
        ),
        migrations.RenameField(
            model_name="player",
            old_name="playerID",
            new_name="player_id",
        ),
        migrations.RenameField(
            model_name="player",
            old_name="playerMainPosition",
            new_name="player_main_position",
        ),
        migrations.RenameField(
            model_name="player",
            old_name="playerPowerScore",
            new_name="player_power_score",
        ),
        migrations.RenameField(
            model_name="player",
            old_name="playerSecondaryPosition",
            new_name="player_secondary_position",
        ),
    ]
