# Generated by Django 5.0.6 on 2026-03-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0002_alter_player_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="player_loss",
            field=models.IntegerField(default=0, verbose_name="패"),
        ),
        migrations.AddField(
            model_name="player",
            name="player_win",
            field=models.IntegerField(default=0, verbose_name="승"),
        ),
    ]
