# Generated by Django 5.0.6 on 2026-03-09 06:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0003_player_player_loss_player_player_win"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="player_loss",
            new_name="player_lose",
        ),
    ]
