# Generated by Django 5.0.6 on 2026-03-16 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matches", "0002_match_is_rating_applied"),
        ("players", "0004_rename_player_loss_player_player_lose"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(default=1, verbose_name="경기 반영 리비전"),
                ),
                ("rating_before", models.IntegerField(verbose_name="반영 전 PS")),
                ("rating_after", models.IntegerField(verbose_name="반영 후 PS")),
                ("delta_total", models.IntegerField(verbose_name="총 변화량")),
                ("delta_base", models.FloatField(verbose_name="승패 기반 변화량")),
                ("delta_kp", models.FloatField(verbose_name="킬관여율 보정")),
                ("delta_role", models.FloatField(verbose_name="포지션 보정")),
                ("expected_score", models.FloatField(verbose_name="기대 승률")),
                ("actual_score", models.FloatField(verbose_name="실제 결과")),
                ("kill_participation", models.FloatField(verbose_name="킬관여율")),
                ("team_kills", models.PositiveIntegerField(verbose_name="팀 총 킬")),
                (
                    "lane_preference_type",
                    models.CharField(
                        choices=[
                            ("MAIN", "주포지션"),
                            ("SECONDARY", "부포지션"),
                            ("OFFROLE", "비선호 포지션"),
                        ],
                        max_length=20,
                        verbose_name="포지션 선호도 유형",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_histories",
                        to="matches.match",
                        verbose_name="경기",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_histories",
                        to="players.player",
                        verbose_name="플레이어",
                    ),
                ),
            ],
            options={
                "verbose_name": "레이팅 이력",
                "verbose_name_plural": "레이팅 이력 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
