# Generated by Django 5.0.6 on 2026-03-12 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("players", "0004_rename_player_loss_player_player_lose"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_id",
                    models.CharField(max_length=50, unique=True, verbose_name="경기 ID"),
                ),
                ("win_team", models.IntegerField(verbose_name="승리 팀")),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="match_screenshots/",
                        verbose_name="경기 결과 스크린샷",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchPlayerDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_team", models.IntegerField()),
                ("player_kda", models.CharField(max_length=20)),
                (
                    "player_selected_lane",
                    models.CharField(
                        choices=[
                            ("TOP", "탑"),
                            ("JGL", "정글"),
                            ("MID", "미드"),
                            ("ADC", "원딜"),
                            ("SUP", "서폿"),
                        ],
                        max_length=3,
                    ),
                ),
                ("player_gold", models.IntegerField()),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_details",
                        to="matches.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_details",
                        to="players.player",
                    ),
                ),
            ],
        ),
    ]
