# Generated by Django 5.0.6 on 2026-03-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="is_rating_applied",
            field=models.BooleanField(default=False, verbose_name="레이팅 반영 여부"),
        ),
    ]
